export const PAGE = "page";
export const QUERY = "query";
export const SEARCH = "search";
export const SOMETHING_WENT_WRONG = "Something went wrong!";
export const TRY_AGAIN = "Try again";
export const CANCEL = "Cancel";
export const GO_BACK = "Go back";
export const NOT_FOUND = "404 Not Found";
export const COULD_NOT_FIND = "Could not find the requested .";
